sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:

before_install:
  - composer self-update
  - composer require --dev satooshi/php-coveralls:dev-master squizlabs/php_codesniffer:~2.5

install:
  - composer install --prefer-source --no-interaction
  - mkdir -p coverage

script:
  - php vendor/bin/phpunit --coverage-clover coverage/clover.xml
  - php vendor/bin/phpcs --standard=PSR2 --ignore=vendor/* src tests

after_script:
  - php vendor/bin/coveralls

notififation:
  on_success: never
  on_failure: always
